python transfer_tide.py --bid 0 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 0 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 1 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 1 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 2 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 2 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 3 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 3 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 4 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 4 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 5 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 5 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 6 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 6 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 7 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 7 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 8 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 8 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 9 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 9 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 10 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 10 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 11 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 11 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 12 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 12 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 13 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 13 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 14 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 14 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 16 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 16 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 17 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 17 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 18 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 18 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 19 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 19 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 22 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 22 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 23 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 23 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 24 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 24 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 25 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 25 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 26 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 26 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 27 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 27 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 28 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 28 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 29 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 29 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 30 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 30 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 31 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 31 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 33 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 33 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 34 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 34 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 35 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 35 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 37 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 37 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 38 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 38 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 40 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 40 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 41 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 41 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 42 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 42 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 44 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 44 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 45 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 45 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 46 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 46 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 47 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 47 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 48 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 48 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 51 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 51 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 55 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 55 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 56 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 56 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 62 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 62 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 63 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 63 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 64 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 64 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 65 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 65 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 68 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 68 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 69 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 69 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 72 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 72 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 73 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 73 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 74 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 74 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 75 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 75 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 76 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 76 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 77 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 77 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 78 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 78 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 79 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 79 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 80 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 80 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 81 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 81 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 82 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 82 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 83 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 83 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 84 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 84 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 85 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 85 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 86 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 86 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 87 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 87 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 88 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 88 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 89 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 89 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 90 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 90 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 93 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 93 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 94 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 94 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 95 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 95 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 96 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 96 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 97 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 97 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 98 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 98 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 101 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 101 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 102 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 102 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 106 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 106 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 107 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 107 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 110 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 110 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 111 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 111 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 112 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 112 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 113 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 113 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 114 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 114 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 116 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 116 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 117 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 117 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 119 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 119 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 120 --mode best --n-sources 2 --device 0
python transfer_tide.py --bid 120 --mode worst --n-sources 2 --device 0
python transfer_tide.py --bid 0 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 0 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 1 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 1 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 2 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 2 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 3 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 3 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 4 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 4 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 5 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 5 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 6 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 6 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 7 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 7 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 8 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 8 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 9 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 9 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 10 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 10 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 11 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 11 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 12 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 12 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 13 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 13 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 14 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 14 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 16 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 16 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 17 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 17 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 18 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 18 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 19 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 19 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 22 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 22 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 23 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 23 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 24 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 24 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 25 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 25 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 26 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 26 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 27 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 27 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 28 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 28 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 29 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 29 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 30 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 30 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 31 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 31 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 33 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 33 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 34 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 34 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 35 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 35 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 37 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 37 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 38 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 38 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 40 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 40 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 41 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 41 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 42 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 42 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 44 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 44 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 45 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 45 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 46 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 46 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 47 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 47 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 48 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 48 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 51 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 51 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 55 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 55 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 56 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 56 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 62 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 62 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 63 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 63 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 64 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 64 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 65 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 65 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 68 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 68 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 69 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 69 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 72 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 72 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 73 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 73 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 74 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 74 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 75 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 75 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 76 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 76 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 77 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 77 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 78 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 78 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 79 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 79 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 80 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 80 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 81 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 81 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 82 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 82 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 83 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 83 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 84 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 84 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 85 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 85 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 86 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 86 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 87 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 87 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 88 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 88 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 89 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 89 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 90 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 90 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 93 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 93 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 94 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 94 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 95 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 95 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 96 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 96 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 97 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 97 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 98 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 98 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 101 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 101 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 102 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 102 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 106 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 106 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 107 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 107 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 110 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 110 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 111 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 111 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 112 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 112 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 113 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 113 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 114 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 114 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 116 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 116 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 117 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 117 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 119 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 119 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 120 --mode best --n-sources 4 --device 0
python transfer_tide.py --bid 120 --mode worst --n-sources 4 --device 0
python transfer_tide.py --bid 0 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 0 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 1 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 1 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 2 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 2 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 3 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 3 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 4 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 4 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 5 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 5 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 6 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 6 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 7 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 7 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 8 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 8 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 9 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 9 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 10 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 10 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 11 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 11 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 12 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 12 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 13 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 13 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 14 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 14 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 16 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 16 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 17 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 17 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 18 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 18 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 19 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 19 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 22 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 22 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 23 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 23 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 24 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 24 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 25 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 25 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 26 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 26 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 27 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 27 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 28 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 28 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 29 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 29 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 30 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 30 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 31 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 31 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 33 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 33 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 34 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 34 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 35 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 35 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 37 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 37 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 38 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 38 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 40 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 40 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 41 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 41 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 42 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 42 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 44 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 44 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 45 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 45 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 46 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 46 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 47 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 47 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 48 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 48 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 51 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 51 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 55 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 55 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 56 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 56 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 62 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 62 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 63 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 63 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 64 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 64 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 65 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 65 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 68 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 68 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 69 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 69 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 72 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 72 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 73 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 73 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 74 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 74 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 75 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 75 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 76 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 76 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 77 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 77 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 78 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 78 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 79 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 79 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 80 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 80 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 81 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 81 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 82 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 82 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 83 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 83 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 84 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 84 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 85 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 85 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 86 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 86 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 87 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 87 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 88 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 88 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 89 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 89 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 90 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 90 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 93 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 93 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 94 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 94 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 95 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 95 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 96 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 96 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 97 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 97 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 98 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 98 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 101 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 101 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 102 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 102 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 106 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 106 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 107 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 107 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 110 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 110 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 111 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 111 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 112 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 112 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 113 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 113 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 114 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 114 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 116 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 116 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 117 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 117 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 119 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 119 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 120 --mode best --n-sources 8 --device 0
python transfer_tide.py --bid 120 --mode worst --n-sources 8 --device 0
python transfer_tide.py --bid 0 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 0 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 1 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 1 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 2 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 2 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 3 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 3 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 4 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 4 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 5 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 5 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 6 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 6 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 7 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 7 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 8 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 8 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 9 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 9 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 10 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 10 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 11 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 11 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 12 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 12 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 13 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 13 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 14 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 14 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 16 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 16 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 17 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 17 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 18 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 18 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 19 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 19 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 22 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 22 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 23 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 23 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 24 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 24 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 25 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 25 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 26 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 26 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 27 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 27 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 28 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 28 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 29 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 29 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 30 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 30 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 31 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 31 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 33 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 33 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 34 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 34 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 35 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 35 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 37 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 37 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 38 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 38 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 40 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 40 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 41 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 41 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 42 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 42 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 44 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 44 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 45 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 45 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 46 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 46 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 47 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 47 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 48 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 48 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 51 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 51 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 55 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 55 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 56 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 56 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 62 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 62 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 63 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 63 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 64 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 64 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 65 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 65 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 68 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 68 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 69 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 69 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 72 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 72 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 73 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 73 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 74 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 74 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 75 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 75 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 76 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 76 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 77 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 77 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 78 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 78 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 79 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 79 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 80 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 80 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 81 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 81 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 82 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 82 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 83 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 83 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 84 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 84 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 85 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 85 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 86 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 86 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 87 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 87 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 88 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 88 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 89 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 89 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 90 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 90 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 93 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 93 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 94 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 94 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 95 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 95 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 96 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 96 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 97 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 97 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 98 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 98 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 101 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 101 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 102 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 102 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 106 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 106 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 107 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 107 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 110 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 110 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 111 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 111 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 112 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 112 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 113 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 113 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 114 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 114 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 116 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 116 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 117 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 117 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 119 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 119 --mode worst --n-sources 16 --device 0
python transfer_tide.py --bid 120 --mode best --n-sources 16 --device 0
python transfer_tide.py --bid 120 --mode worst --n-sources 16 --device 0