python transfer_tide.py --bid 0 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 1 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 2 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 3 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 4 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 5 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 6 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 7 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 8 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 9 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 10 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 11 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 12 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 13 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 14 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 16 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 17 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 18 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 19 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 22 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 23 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 24 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 25 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 26 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 27 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 28 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 29 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 30 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 31 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 33 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 34 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 35 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 37 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 38 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 40 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 41 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 42 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 44 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 45 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 46 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 47 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 48 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 51 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 55 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 56 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 62 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 63 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 64 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 65 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 68 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 69 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 72 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 73 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 74 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 75 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 76 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 77 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 78 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 79 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 80 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 81 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 82 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 83 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 84 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 85 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 86 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 87 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 88 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 89 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 90 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 93 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 94 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 95 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 96 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 97 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 98 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 101 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 102 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 106 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 107 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 110 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 111 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 112 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 113 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 114 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 116 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 117 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 119 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 120 --mode none --n-sources 2 --device 1
python transfer_tide.py --bid 0 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 1 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 2 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 3 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 4 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 5 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 6 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 7 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 8 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 9 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 10 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 11 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 12 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 13 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 14 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 16 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 17 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 18 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 19 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 22 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 23 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 24 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 25 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 26 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 27 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 28 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 29 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 30 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 31 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 33 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 34 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 35 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 37 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 38 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 40 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 41 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 42 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 44 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 45 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 46 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 47 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 48 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 51 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 55 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 56 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 62 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 63 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 64 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 65 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 68 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 69 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 72 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 73 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 74 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 75 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 76 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 77 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 78 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 79 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 80 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 81 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 82 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 83 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 84 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 85 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 86 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 87 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 88 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 89 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 90 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 93 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 94 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 95 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 96 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 97 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 98 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 101 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 102 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 106 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 107 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 110 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 111 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 112 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 113 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 114 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 116 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 117 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 119 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 120 --mode none --n-sources 4 --device 1
python transfer_tide.py --bid 0 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 1 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 2 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 3 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 4 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 5 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 6 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 7 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 8 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 9 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 10 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 11 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 12 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 13 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 14 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 16 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 17 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 18 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 19 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 22 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 23 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 24 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 25 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 26 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 27 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 28 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 29 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 30 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 31 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 33 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 34 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 35 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 37 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 38 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 40 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 41 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 42 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 44 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 45 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 46 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 47 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 48 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 51 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 55 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 56 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 62 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 63 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 64 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 65 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 68 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 69 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 72 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 73 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 74 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 75 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 76 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 77 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 78 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 79 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 80 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 81 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 82 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 83 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 84 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 85 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 86 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 87 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 88 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 89 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 90 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 93 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 94 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 95 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 96 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 97 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 98 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 101 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 102 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 106 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 107 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 110 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 111 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 112 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 113 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 114 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 116 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 117 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 119 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 120 --mode none --n-sources 8 --device 1
python transfer_tide.py --bid 0 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 1 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 2 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 3 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 4 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 5 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 6 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 7 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 8 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 9 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 10 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 11 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 12 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 13 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 14 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 16 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 17 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 18 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 19 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 22 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 23 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 24 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 25 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 26 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 27 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 28 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 29 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 30 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 31 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 33 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 34 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 35 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 37 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 38 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 40 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 41 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 42 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 44 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 45 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 46 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 47 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 48 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 51 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 55 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 56 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 62 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 63 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 64 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 65 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 68 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 69 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 72 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 73 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 74 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 75 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 76 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 77 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 78 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 79 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 80 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 81 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 82 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 83 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 84 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 85 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 86 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 87 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 88 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 89 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 90 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 93 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 94 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 95 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 96 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 97 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 98 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 101 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 102 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 106 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 107 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 110 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 111 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 112 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 113 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 114 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 116 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 117 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 119 --mode none --n-sources 16 --device 1
python transfer_tide.py --bid 120 --mode none --n-sources 16 --device 1